In [2]:
import pandas as pd
ds=pd.read_csv("/content/Bipolarf.csv")
ds

,Name,Age,Gender,Little interest in work,Feeling hopeless,Feeling angry than usual,high energy,doing more risky things,Feeling nervous,panic,...,sleep quality,Stomach pain,Back pain,joints pain,awful might happen,worried,felt nervous,scared easily,worried when away from home,category
0,Aaa,16,Female,1,2,1,1,2,1,0,...,3,1,0,0,3,3,3,1,1,n
1,Abhinivesh S,19,Male,1,1,1,1,1,3,3,...,4,0,0,0,3,4,3,4,3,m
2,Abhishek,15,Male,1,1,0,2,0,1,0,...,5,0,0,0,3,2,2,3,4,n
3,Abinaya S,16,Female,3,1,1,2,1,1,0,...,3,0,0,0,3,3,3,1,1,n
4,Abinaya S,19,Female,1,1,0,0,3,2,0,...,3,0,0,1,1,2,2,4,3,d
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,Swetha,19,Female,2,2,2,2,2,2,2,...,4,2,2,2,3,4,3,2,2,m
63,Varsha,17,Female,3,3,2,3,0,3,3,...,3,1,0,0,5,4,2,2,5,m
64,Vishnupriya.S,20,Female,1,1,2,0,0,1,1,...,5,1,1,0,3,4,3,3,1,h
65,Visruthi,17,Female,2,3,2,2,0,2,3,...,2,1,1,1,5,5,4,4,4,m
66,Visweswara S M,20,Male,3,1,1,1,1,2,2,...,3,0,0,1,4,3,3,3,4,h

In [3]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 48 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Name                                67 non-null     object
 1   Age                                 67 non-null     int64
 2   Gender                              67 non-null     object
 3   Little interest in work             67 non-null     int64
 4   Feeling hopeless                    67 non-null     int64
 5   Feeling angry than usual            67 non-null     int64
 6   high energy                         67 non-null     int64
 7   doing more risky things             67 non-null     int64
 8   Feeling nervous                     67 non-null     int64
 9   panic                               67 non-null     int64
 10  Avoiding anxious situations         67 non-null     int64
 11  illnesses are not taken seriously   67 non-null     int64
 12  Thoughts of hurting yourself?       67 non-null     int64
 13  Sleep prob affecting sleep quality  67 non-null     int64
 14  memory problems                     67 non-null     int64
 15  repeated Unpleasant thoughts        67 non-null     int64
 16  Not feeling close to people         67 non-null     int64
 17  felt alone                          67 non-null     int64
 18  felt stressed                       67 non-null     int64
 19  feeling sad                         67 non-null     int64
 20  being myself                        67 non-null     int64
 21  hard to have fun.                   67 non-null     int64
 22  easily annoyed                      67 non-null     int64
 23  lose temper                         67 non-null     int64
 24  frequent anger                      67 non-null     int64
 25  Lose temper                         67 non-null     int64
 26  irritability problems               67 non-null     int64
 27  qnconfident                         67 non-null     int64
 28  qnsleep                             67 non-null     int64
 29  qntalk                              67 non-null     int64
 30  thoughts duration                   67 non-null     int64
 31  bothering                           67 non-null     int64
 32  thoughts control                    67 non-null     int64
 33  thoughts interference               67 non-null     int64
 34  Restlessleep                        67 non-null     int64
 35  sleepsatisfaction                   67 non-null     int64
 36  refreshment                         67 non-null     int64
 37  diffallsleep                        67 non-null     int64
 38  sleep quality                       67 non-null     int64
 39  Stomach pain                        67 non-null     int64
 40  Back pain                           67 non-null     int64
 41  joints pain                         67 non-null     int64
 42  awful might happen                  67 non-null     int64
 43  worried                             67 non-null     int64
 44  felt nervous                        67 non-null     int64
 45  scared easily                       67 non-null     int64
 46  worried when away from home         67 non-null     int64
 47  category                            67 non-null     object
dtypes: int64(45), object(3)
memory usage: 25.2+ KB

In [4]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
ds['Gender']=le.fit_transform(ds['Gender'])
ds['Gender']=pd.DataFrame(ds['Gender'])

In [5]:

ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 48 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Name                                67 non-null     object
 1   Age                                 67 non-null     int64
 2   Gender                              67 non-null     int64
 3   Little interest in work             67 non-null     int64
 4   Feeling hopeless                    67 non-null     int64
 5   Feeling angry than usual            67 non-null     int64
 6   high energy                         67 non-null     int64
 7   doing more risky things             67 non-null     int64
 8   Feeling nervous                     67 non-null     int64
 9   panic                               67 non-null     int64
 10  Avoiding anxious situations         67 non-null     int64
 11  illnesses are not taken seriously   67 non-null     int64
 12  Thoughts of hurting yourself?       67 non-null     int64
 13  Sleep prob affecting sleep quality  67 non-null     int64
 14  memory problems                     67 non-null     int64
 15  repeated Unpleasant thoughts        67 non-null     int64
 16  Not feeling close to people         67 non-null     int64
 17  felt alone                          67 non-null     int64
 18  felt stressed                       67 non-null     int64
 19  feeling sad                         67 non-null     int64
 20  being myself                        67 non-null     int64
 21  hard to have fun.                   67 non-null     int64
 22  easily annoyed                      67 non-null     int64
 23  lose temper                         67 non-null     int64
 24  frequent anger                      67 non-null     int64
 25  Lose temper                         67 non-null     int64
 26  irritability problems               67 non-null     int64
 27  qnconfident                         67 non-null     int64
 28  qnsleep                             67 non-null     int64
 29  qntalk                              67 non-null     int64
 30  thoughts duration                   67 non-null     int64
 31  bothering                           67 non-null     int64
 32  thoughts control                    67 non-null     int64
 33  thoughts interference               67 non-null     int64
 34  Restlessleep                        67 non-null     int64
 35  sleepsatisfaction                   67 non-null     int64
 36  refreshment                         67 non-null     int64
 37  diffallsleep                        67 non-null     int64
 38  sleep quality                       67 non-null     int64
 39  Stomach pain                        67 non-null     int64
 40  Back pain                           67 non-null     int64
 41  joints pain                         67 non-null     int64
 42  awful might happen                  67 non-null     int64
 43  worried                             67 non-null     int64
 44  felt nervous                        67 non-null     int64
 45  scared easily                       67 non-null     int64
 46  worried when away from home         67 non-null     int64
 47  category                            67 non-null     object
dtypes: int64(46), object(2)
memory usage: 25.2+ KB

In [6]:
sums=ds.sum(axis=1)

<ipython-input-6-93ab1f416720>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  sums=ds.sum(axis=1)

In [7]:
print("Sno--Score")
print(sums)

Sno--Score
0      85
1     107
2      83
3      87
4      96
     ...
62    128
63    123
64     98
65    126
66    103
Length: 67, dtype: int64

In [8]:
tot=0
for i in sums:
    tot=tot+i
    res=tot/67

print(res)

97.77611940298507

In [9]:
thres=97.7;
if thres > 97.7:
    printf("You should consult the Doctor")

In [10]:
for i in sums:
    if i>thres:
        print(i)

107
107
128
100
115
121
105
104
120
119
101
117
108
124
102
137
112
115
112
113
109
104
99
145
111
128
107
101
128
123
98
126
103

In [11]:
ds.columns

Index(['Name', 'Age', 'Gender', 'Little interest in work',
       'Feeling hopeless  ', 'Feeling angry than usual', 'high energy',
       'doing more risky things ', 'Feeling nervous', 'panic',
       'Avoiding anxious situations  ', 'illnesses are not taken seriously ',
       'Thoughts of hurting yourself?', 'Sleep prob affecting sleep quality',
       'memory problems', 'repeated Unpleasant thoughts',
       'Not feeling close to people ', 'felt alone', 'felt stressed',
       'feeling sad', 'being myself', 'hard to have fun.', 'easily annoyed',
       'lose temper', 'frequent anger', 'Lose temper', 'irritability problems',
       'qnconfident', 'qnsleep', 'qntalk', 'thoughts duration', 'bothering',
       'thoughts control', 'thoughts interference', 'Restlessleep',
       'sleepsatisfaction', 'refreshment', 'diffallsleep', 'sleep quality',
       'Stomach pain', 'Back pain', 'joints pain', 'awful might happen',
       'worried', 'felt nervous', 'scared easily',
       'worried when away from home', 'category'],
      dtype='object')

In [12]:
mania=ds[['Restlessleep','diffallsleep','sleepsatisfaction','Sleep prob affecting sleep quality',
          'qnconfident','qntalk','thoughts duration','bothering','thoughts control','repeated Unpleasant thoughts','Feeling angry than usual']]

In [13]:
x1=mania.sum(axis=1)

In [14]:
print(x1)

0     18
1     23
2     18
3     21
4     23
      ..
62    28
63    27
64    21
65    29
66    21
Length: 67, dtype: int64

In [15]:
tot=0
for i in x1:
    tot=tot+i
    res1=tot/67

print(res1)

21.47761194029851

In [16]:
man=[]
for i in range(len(x1)):
    if x1[i]>res1:
        man.append(i)

print("IDs with mania")
print(man)

IDs with mania
[1, 4, 5, 9, 10, 11, 12, 15, 16, 20, 22, 27, 28, 29, 30, 33, 34, 37, 38, 44, 47, 51, 53, 54, 55, 56, 57, 62, 63, 65]

In [17]:
ds.columns

Index(['Name', 'Age', 'Gender', 'Little interest in work',
       'Feeling hopeless  ', 'Feeling angry than usual', 'high energy',
       'doing more risky things ', 'Feeling nervous', 'panic',
       'Avoiding anxious situations  ', 'illnesses are not taken seriously ',
       'Thoughts of hurting yourself?', 'Sleep prob affecting sleep quality',
       'memory problems', 'repeated Unpleasant thoughts',
       'Not feeling close to people ', 'felt alone', 'felt stressed',
       'feeling sad', 'being myself', 'hard to have fun.', 'easily annoyed',
       'lose temper', 'frequent anger', 'Lose temper', 'irritability problems',
       'qnconfident', 'qnsleep', 'qntalk', 'thoughts duration', 'bothering',
       'thoughts control', 'thoughts interference', 'Restlessleep',
       'sleepsatisfaction', 'refreshment', 'diffallsleep', 'sleep quality',
       'Stomach pain', 'Back pain', 'joints pain', 'awful might happen',
       'worried', 'felt nervous', 'scared easily',
       'worried when away from home', 'category'],
      dtype='object')

In [18]:
hypomania=ds[['qntalk','being myself','Thoughts of hurting yourself?','Feeling nervous','worried','panic']]

In [19]:
x2=hypomania.sum(axis=1)

In [20]:
print(x2)

0     11
1     18
2      6
3     12
4     11
      ..
62    18
63    18
64    14
65    20
66    13
Length: 67, dtype: int64

In [21]:
tot=0
for i in x2:
    tot=tot+i
    res2=tot/67

print(res2)

11.686567164179104

In [22]:
hyp=[]
for i in range(len(x2)):
    if x2[i]>res2:
        hyp.append(i)
print("IDs with hypomania")
print(hyp)

IDs with hypomania
[1, 3, 5, 8, 9, 10, 11, 12, 14, 16, 18, 20, 21, 22, 24, 27, 29, 30, 34, 41, 43, 44, 45, 51, 53, 54, 55, 56, 60, 62, 63, 64, 65, 66]

In [23]:
ds.columns

Index(['Name', 'Age', 'Gender', 'Little interest in work',
       'Feeling hopeless  ', 'Feeling angry than usual', 'high energy',
       'doing more risky things ', 'Feeling nervous', 'panic',
       'Avoiding anxious situations  ', 'illnesses are not taken seriously ',
       'Thoughts of hurting yourself?', 'Sleep prob affecting sleep quality',
       'memory problems', 'repeated Unpleasant thoughts',
       'Not feeling close to people ', 'felt alone', 'felt stressed',
       'feeling sad', 'being myself', 'hard to have fun.', 'easily annoyed',
       'lose temper', 'frequent anger', 'Lose temper', 'irritability problems',
       'qnconfident', 'qnsleep', 'qntalk', 'thoughts duration', 'bothering',
       'thoughts control', 'thoughts interference', 'Restlessleep',
       'sleepsatisfaction', 'refreshment', 'diffallsleep', 'sleep quality',
       'Stomach pain', 'Back pain', 'joints pain', 'awful might happen',
       'worried', 'felt nervous', 'scared easily',
       'worried when away from home', 'category'],
      dtype='object')

In [24]:
MDE=ds[['feeling sad','Little interest in work','Restlessleep','diffallsleep','sleepsatisfaction','refreshment','Sleep prob affecting sleep quality','high energy','sleep quality','repeated Unpleasant thoughts','thoughts duration','bothering','thoughts control']]

In [25]:
x3=MDE.sum(axis=1)

In [26]:
print(x3)

0     27
1     31
2     28
3     28
4     27
      ..
62    38
63    38
64    28
65    33
66    30
Length: 67, dtype: int64

In [27]:
tot=0
for i in x3:
    tot=tot+i
    res3=tot/67

print(res3)

28.29850746268657

In [28]:
dep=[]
for i in range(len(x3)):
    if x3[i]>res3:
        dep.append(i)
print("IDs with Depression")
print(dep)

IDs with Depression
[1, 5, 9, 11, 12, 14, 15, 20, 22, 24, 27, 28, 29, 33, 34, 35, 37, 38, 39, 44, 45, 47, 48, 49, 53, 54, 55, 57, 60, 62, 63, 65, 66]

# training DS

In [29]:
import pandas as pd
df=pd.read_csv("/content/Bipolarf.csv")

In [30]:
df

,Name,Age,Gender,Little interest in work,Feeling hopeless,Feeling angry than usual,high energy,doing more risky things,Feeling nervous,panic,...,sleep quality,Stomach pain,Back pain,joints pain,awful might happen,worried,felt nervous,scared easily,worried when away from home,category
0,Aaa,16,Female,1,2,1,1,2,1,0,...,3,1,0,0,3,3,3,1,1,n
1,Abhinivesh S,19,Male,1,1,1,1,1,3,3,...,4,0,0,0,3,4,3,4,3,m
2,Abhishek,15,Male,1,1,0,2,0,1,0,...,5,0,0,0,3,2,2,3,4,n
3,Abinaya S,16,Female,3,1,1,2,1,1,0,...,3,0,0,0,3,3,3,1,1,n
4,Abinaya S,19,Female,1,1,0,0,3,2,0,...,3,0,0,1,1,2,2,4,3,d
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,Swetha,19,Female,2,2,2,2,2,2,2,...,4,2,2,2,3,4,3,2,2,m
63,Varsha,17,Female,3,3,2,3,0,3,3,...,3,1,0,0,5,4,2,2,5,m
64,Vishnupriya.S,20,Female,1,1,2,0,0,1,1,...,5,1,1,0,3,4,3,3,1,h
65,Visruthi,17,Female,2,3,2,2,0,2,3,...,2,1,1,1,5,5,4,4,4,m
66,Visweswara S M,20,Male,3,1,1,1,1,2,2,...,3,0,0,1,4,3,3,3,4,h

In [31]:
df=df.drop(['Name'],axis=1)

In [32]:
x=df.iloc[:,:-1]
y=df["category"]

In [33]:
x

,Age,Gender,Little interest in work,Feeling hopeless,Feeling angry than usual,high energy,doing more risky things,Feeling nervous,panic,Avoiding anxious situations,...,diffallsleep,sleep quality,Stomach pain,Back pain,joints pain,awful might happen,worried,felt nervous,scared easily,worried when away from home
0,16,Female,1,2,1,1,2,1,0,0,...,2,3,1,0,0,3,3,3,1,1
1,19,Male,1,1,1,1,1,3,3,2,...,3,4,0,0,0,3,4,3,4,3
2,15,Male,1,1,0,2,0,1,0,3,...,3,5,0,0,0,3,2,2,3,4
3,16,Female,3,1,1,2,1,1,0,0,...,3,3,0,0,0,3,3,3,1,1
4,19,Female,1,1,0,0,3,2,0,3,...,4,3,0,0,1,1,2,2,4,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,19,Female,2,2,2,2,2,2,2,2,...,5,4,2,2,2,3,4,3,2,2
63,17,Female,3,3,2,3,0,3,3,0,...,3,3,1,0,0,5,4,2,2,5
64,20,Female,1,1,2,0,0,1,1,2,...,1,5,1,1,0,3,4,3,3,1
65,17,Female,2,3,2,2,0,2,3,1,...,4,2,1,1,1,5,5,4,4,4
66,20,Male,3,1,1,1,1,2,2,1,...,4,3,0,0,1,4,3,3,3,4

In [34]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])
df['category']=le.fit_transform(df['category'])

In [35]:
df['Gender'] = df['Gender'].astype(float)

In [36]:
df #3-n,2-m,0-d,1-h

,Age,Gender,Little interest in work,Feeling hopeless,Feeling angry than usual,high energy,doing more risky things,Feeling nervous,panic,Avoiding anxious situations,...,sleep quality,Stomach pain,Back pain,joints pain,awful might happen,worried,felt nervous,scared easily,worried when away from home,category
0,16,0.0,1,2,1,1,2,1,0,0,...,3,1,0,0,3,3,3,1,1,3
1,19,1.0,1,1,1,1,1,3,3,2,...,4,0,0,0,3,4,3,4,3,2
2,15,1.0,1,1,0,2,0,1,0,3,...,5,0,0,0,3,2,2,3,4,3
3,16,0.0,3,1,1,2,1,1,0,0,...,3,0,0,0,3,3,3,1,1,3
4,19,0.0,1,1,0,0,3,2,0,3,...,3,0,0,1,1,2,2,4,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,19,0.0,2,2,2,2,2,2,2,2,...,4,2,2,2,3,4,3,2,2,2
63,17,0.0,3,3,2,3,0,3,3,0,...,3,1,0,0,5,4,2,2,5,2
64,20,0.0,1,1,2,0,0,1,1,2,...,5,1,1,0,3,4,3,3,1,1
65,17,0.0,2,3,2,2,0,2,3,1,...,2,1,1,1,5,5,4,4,4,2
66,20,1.0,3,1,1,1,1,2,2,1,...,3,0,0,1,4,3,3,3,4,1

In [37]:
x=df.iloc[:,:-1]
y=df["category"]

In [38]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=43)

In [39]:
x_train.shape,x_test.shape

((46, 46), (21, 46))

# **NAIVE** **BAYES**

In [40]:
from sklearn.naive_bayes import GaussianNB

In [41]:
x_train

,Age,Gender,Little interest in work,Feeling hopeless,Feeling angry than usual,high energy,doing more risky things,Feeling nervous,panic,Avoiding anxious situations,...,diffallsleep,sleep quality,Stomach pain,Back pain,joints pain,awful might happen,worried,felt nervous,scared easily,worried when away from home
45,18,0.0,2,3,2,2,0,3,2,3,...,1,5,1,2,1,3,3,3,3,2
38,15,1.0,2,0,0,2,3,0,0,1,...,5,4,0,0,1,1,1,2,3,5
44,18,0.0,1,1,1,0,0,3,3,2,...,4,5,2,1,2,3,5,5,5,5
3,16,0.0,3,1,1,2,1,1,0,0,...,3,3,0,0,0,3,3,3,1,1
53,20,0.0,2,3,3,2,3,3,3,3,...,3,3,1,1,1,4,4,4,4,4
66,20,1.0,3,1,1,1,1,2,2,1,...,4,3,0,0,1,4,3,3,3,4
8,19,0.0,1,0,1,2,2,3,2,1,...,1,4,1,1,1,2,3,4,1,3
15,13,0.0,3,2,3,2,0,0,0,1,...,4,2,1,0,1,4,4,3,4,1
20,14,0.0,2,2,3,2,3,2,1,1,...,1,5,2,0,2,3,4,4,2,4
29,14,1.0,2,2,3,1,2,3,3,2,...,3,1,1,2,1,3,5,4,5,3
7,13,0.0,1,0,1,3,3,3,3,2,...,1,5,0,0,0,1,1,2,4,4
41,19,0.0,2,0,0,0,0,1,0,0,...,1,5,1,1,0,1,2,2,4,1
28,14,0.0,2,3,3,1,2,2,1,0,...,1,5,1,2,1,5,3,3,2,2
42,19,1.0,3,1,0,0,1,1,1,1,...,1,4,1,0,0,2,2,3,3,3
56,14,0.0,1,0,2,2,3,3,2,1,...,4,2,1,0,2,1,4,5,5,4
9,20,1.0,2,3,2,0,0,3,3,3,...,1,2,0,1,1,3,3,4,5,5
10,19,0.0,1,1,0,1,0,0,0,3,...,3,3,1,2,1,3,3,3,1,3
32,19,1.0,1,1,0,3,1,2,0,1,...,3,5,1,2,0,4,3,2,2,4
24,19,0.0,2,2,0,0,1,2,3,3,...,2,4,1,0,0,3,4,5,5,2
12,20,0.0,3,3,2,0,1,0,2,1,...,1,5,1,0,2,3,3,3,4,3
36,14,1.0,2,0,0,3,0,1,1,1,...,3,4,0,0,0,1,2,1,3,2
4,19,0.0,1,1,0,0,3,2,0,3,...,4,3,0,0,1,1,2,2,4,3
52,19,1.0,2,2,1,0,1,1,0,0,...,4,3,0,0,1,3,2,5,4,3
57,15,1.0,1,0,2,1,0,1,2,1,...,2,4,0,0,1,3,3,3,4,4
61,14,1.0,3,0,0,0,0,0,0,0,...,1,3,0,0,0,1,1,1,1,4
34,20,1.0,2,1,1,2,3,2,1,2,...,3,3,1,0,1,3,3,2,3,4
47,19,0.0,1,1,1,0,1,0,0,2,...,1,5,1,2,1,4,3,3,3,3
1,19,1.0,1,1,1,1,1,3,3,2,...,3,4,0,0,0,3,4,3,4,3
25,16,0.0,2,3,0,0,0,2,2,3,...,2,3,1,2,2,3,2,4,2,5
11,22,1.0,1,3,2,2,2,1,2,2,...,1,4,0,0,1,2,3,3,3,3
50,14,1.0,0,2,2,0,0,0,0,0,...,1,4,0,0,0,3,1,3,3,1
35,20,1.0,2,0,0,2,3,0,0,0,...,2,5,0,2,1,3,1,1,2,2
0,16,0.0,1,2,1,1,2,1,0,0,...,2,3,1,0,0,3,3,3,1,1
23,14,1.0,0,0,0,0,2,2,2,1,...,1,4,0,0,0,3,1,3,3,1
30,14,0.0,3,0,2,3,3,3,3,1,...,4,3,1,2,0,5,5,5,5,4
46,14,1.0,2,3,2,2,0,0,1,1,...,1,5,0,0,0,4,2,2,4,1
2,15,1.0,1,1,0,2,0,1,0,3,...,3,5,0,0,0,3,2,2,3,4
27,19,0.0,2,3,3,3,3,1,1,3,...,5,2,0,0,1,3,5,3,2,1
59,19,1.0,1,1,0,0,0,1,0,0,...,1,4,1,2,1,3,3,3,1,5
17,14,1.0,3,0,2,1,1,1,0,1,...,1,5,1,0,0,1,1,1,2,3
51,19,0.0,3,2,1,1,0,0,0,0,...,4,3,2,1,0,3,3,3,2,1
16,20,0.0,0,3,3,3,3,3,3,3,...,2,4,1,0,2,3,4,3,5,4
58,20,1.0,2,0,0,3,2,0,0,1,...,2,4,0,1,1,3,3,3,1,2
21,19,0.0,2,1,1,2,2,2,2,2,...,2,3,1,1,1,2,3,3,3,3
49,19,0.0,1,1,0,0,1,1,0,0,...,1,4,1,2,0,3,3,3,2,3
64,20,0.0,1,1,2,0,0,1,1,2,...,1,5,1,1,0,3,4,3,3,1

In [42]:
gnb = GaussianNB()
gnb.fit(x_train,y_train)
y_pred = gnb.predict(x_test)

In [43]:
from sklearn import metrics
print("accuracy:",metrics.accuracy_score(y_test,y_pred))

accuracy: 0.7142857142857143

# rfc

In [44]:
from sklearn.ensemble import RandomForestClassifier
class_rf=RandomForestClassifier(random_state=13,n_jobs=-1,max_depth=3,n_estimators=70,oob_score=True)
class_rf.fit(x,y)

RandomForestClassifier(max_depth=3, n_estimators=70, n_jobs=-1, oob_score=True,
                       random_state=13)

In [45]:
ypred=class_rf.predict(x_test)
ypred

array([3, 2, 0, 3, 2, 2, 2, 3, 2, 1, 3, 0, 2, 2, 2, 3, 2, 3, 2, 2, 2])

In [46]:
%%time
class_rf.fit(x_train,y_train)

CPU times: user 168 ms, sys: 24.3 ms, total: 193 ms
Wall time: 173 ms

RandomForestClassifier(max_depth=3, n_estimators=70, n_jobs=-1, oob_score=True,
                       random_state=13)

In [47]:
class_rf.oob_score_

0.6739130434782609

In [48]:
%%time
class_rf.fit(x_test,y_test)

CPU times: user 171 ms, sys: 17.9 ms, total: 189 ms
Wall time: 170 ms

RandomForestClassifier(max_depth=3, n_estimators=70, n_jobs=-1, oob_score=True,
                       random_state=13)

In [49]:
class_rf.oob_score_

0.6190476190476191

# DT

In [50]:
#decision tree classifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
dt=DecisionTreeClassifier(criterion="gini",random_state=13)
dt=dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)
y_pred

array([3, 2, 3, 3, 2, 2, 2, 3, 2, 3, 3, 3, 2, 0, 2, 3, 2, 3, 2, 2, 2])

In [51]:
print("accuracy:",metrics.accuracy_score(y_test,y_pred))

accuracy: 0.6666666666666666

# Hyper Tuning

In [52]:
from sklearn.model_selection import RepeatedStratifiedKFold
cv = RepeatedStratifiedKFold(n_splits=9, n_repeats=2, random_state=1)

In [53]:
from scipy.stats import loguniform
space=dict()
space['min_impurity_decrease'] = [0.0,0.1,0.4]
space['max_leaf_nodes'] = [2,3,4,5]
space['max_depth'] =[4,5,6,8,10]
space['random_state'] =[11,12,13]

In [54]:
from sklearn.model_selection import RandomizedSearchCV
search = RandomizedSearchCV(dt, space, n_iter=500, scoring='accuracy', n_jobs=-1, cv=cv, random_state=1,error_score='raise')
result = search.fit(x, y)
print('Best Score: %s' % result.best_score_)
print('Best Hyperparameters: %s' % result.best_params_)

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py:305: UserWarning: The total space of parameters 180 is smaller than n_iter=500. Running 180 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 7 members, which is less than n_splits=9.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 7 members, which is less than n_splits=9.
  warnings.warn(

Best Score: 0.6438492063492062
Best Hyperparameters: {'random_state': 11, 'min_impurity_decrease': 0.0, 'max_leaf_nodes': 2, 'max_depth': 4}

In [55]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
cls = DecisionTreeClassifier(max_depth=4,max_leaf_nodes=2,min_impurity_decrease=0.0,random_state=11)
model = cls.fit(x_train,y_train)
model

DecisionTreeClassifier(max_depth=4, max_leaf_nodes=2, random_state=11)

In [56]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
ac=accuracy_score(y_test,y_pred)
cr=classification_report(y_test,y_pred)
print("Accuracy :",ac)
print(cr)

Accuracy : 0.6666666666666666
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         4
           1       0.00      0.00      0.00         2
           2       0.73      0.89      0.80         9
           3       0.67      1.00      0.80         6

    accuracy                           0.67        21
   macro avg       0.35      0.47      0.40        21
weighted avg       0.50      0.67      0.57        21

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [57]:
from scipy.stats import loguniform
spaces=dict()
spaces['min_impurity_decrease'] = [0.0,0.1,0.2,0.4]
spaces['max_leaf_nodes'] = [4,5,6,7]
spaces['max_depth'] =[1,2,3,4]
spaces['random_state']=[20,10,30]

In [58]:
from sklearn.model_selection import GridSearchCV
searchs = GridSearchCV(model, spaces, scoring='accuracy', n_jobs=-1, cv=cv,error_score='raise')

In [59]:
results = searchs.fit(x, y)
print('Best Score: %s' % results.best_score_)
print('Best Hyperparameters: %s' % results.best_params_)

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 7 members, which is less than n_splits=9.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 7 members, which is less than n_splits=9.
  warnings.warn(

Best Score: 0.6438492063492062
Best Hyperparameters: {'max_depth': 1, 'max_leaf_nodes': 4, 'min_impurity_decrease': 0.0, 'random_state': 20}

In [60]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
cls = DecisionTreeClassifier(max_depth=1,max_leaf_nodes=4,min_impurity_decrease=0.0,random_state=20)
model = cls.fit(x_train,y_train)
model

DecisionTreeClassifier(max_depth=1, max_leaf_nodes=4, random_state=20)

In [61]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
ac=accuracy_score(y_test,y_pred)
cr=classification_report(y_test,y_pred)
print("Accuracy :",ac)
print(cr)

Accuracy : 0.6666666666666666
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         4
           1       0.00      0.00      0.00         2
           2       0.73      0.89      0.80         9
           3       0.67      1.00      0.80         6

    accuracy                           0.67        21
   macro avg       0.35      0.47      0.40        21
weighted avg       0.50      0.67      0.57        21

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [ ]:
pickle.dump(le,open("labelencod.pkl","wb"))
pickle.dump(dt,open("dectree.pkl","wb"))